In [3]:
import torch
from torch import nn

layer = nn.BatchNorm1d(3)
# nn.Linear는 weight가 랜덤 초기화인데 반해 얘는 1,0으로 초기화되어있음.
# 배치 정규화 : a((x-x바)/시그마)+b 에서 a가 weight b가 bias

print(layer.weight) # 표준편차
print(layer.bias) # 평균

x = torch.randn(5,3)
print(x)
print(layer(x))

Parameter containing:
tensor([1., 1., 1.], requires_grad=True)
Parameter containing:
tensor([0., 0., 0.], requires_grad=True)
tensor([[ 0.7804,  0.5485,  0.9072],
        [-0.4048, -1.3255,  0.6525],
        [ 1.2262, -0.6457,  0.6408],
        [-1.5030,  0.2380,  1.8559],
        [-0.2926, -1.5285, -0.5278]])
tensor([[ 0.8527,  1.3241,  0.2649],
        [-0.3810, -0.9500, -0.0700],
        [ 1.3169, -0.1250, -0.0853],
        [-1.5243,  0.9473,  1.5123],
        [-0.2643, -1.1964, -1.6219]], grad_fn=<NativeBatchNormBackward0>)


In [4]:
layer = nn.BatchNorm2d(3)
print(layer.weight) # 표준편차
print(layer.bias) # 평균

x = torch.randn(5,3,32,32)
print(layer(x).shape)
# 2d 사용시 shape은 유지됨
# 이때 배치 정규화 레이어에 들어가는 숫자는 무조건 채널의 갯수와 맞춰야함
# 이는 채널별로 독립적으로 적용됨

Parameter containing:
tensor([1., 1., 1.], requires_grad=True)
Parameter containing:
tensor([0., 0., 0.], requires_grad=True)
torch.Size([5, 3, 32, 32])


In [9]:
x = torch.randn(3,7)
drop = nn.Dropout(p=0.1)
# 이론에서는 p는 살릴확률이지만 구현에서 p는 죽일 확률
print(x)
print()
print(drop(x)) # 좀더 커지는 것을 볼 수 있음
print()
print(drop(x)*(1-0.1)) # 이렇게 해줘야 x와 값은 똑같음
# 이론에서는 테스트시 1-p(살아남을 확률)을 곱해서 출력을 유지시켜줌
# 구현은 반대로 훈련 때 1/살릴 확률(1-p)을 곱하고 테스트 때는 그대로
# 즉 구현에서 학습때 이미 키워줬으므로 테스트때 아무것도 안해도되므로 효율적임

print()
drop.eval()
print(drop(x))

tensor([[-0.3377,  2.5054,  2.3935, -1.4460,  0.8651,  0.4030,  1.8704],
        [-1.1407,  1.3994,  0.1711,  0.2853,  0.0858, -0.4347,  0.8774],
        [-0.9355, -1.7799,  1.5643, -0.8744,  0.3399,  0.2866,  0.4138]])

tensor([[-0.3752,  2.7838,  2.6594, -1.6067,  0.9613,  0.0000,  2.0782],
        [-1.2674,  1.5549,  0.1901,  0.3170,  0.0953, -0.0000,  0.9749],
        [-1.0394, -0.0000,  1.7381, -0.9716,  0.3776,  0.3184,  0.4598]])

tensor([[-0.3377,  2.5054,  2.3935, -1.4460,  0.8651,  0.4030,  1.8704],
        [-1.1407,  1.3994,  0.1711,  0.2853,  0.0858, -0.0000,  0.8774],
        [-0.9355, -1.7799,  1.5643, -0.8744,  0.3399,  0.2866,  0.4138]])

tensor([[-0.3377,  2.5054,  2.3935, -1.4460,  0.8651,  0.4030,  1.8704],
        [-1.1407,  1.3994,  0.1711,  0.2853,  0.0858, -0.4347,  0.8774],
        [-0.9355, -1.7799,  1.5643, -0.8744,  0.3399,  0.2866,  0.4138]])
